#!/bin/bash

# There are input as a filename

if [ "$#" -ne 1 ]; then 
    echo "I take one argument and one argument only: a file name"
    exit 1
fi
if [[ $1 == '/'* || $1 == '~'* ]]; then
    echo $1
    path=$1
else 
    path="$(pwd)/$1"
fi
echo $path
if [ -f $path ]; then
    buffer=$path"_buffer"
    echo "Checking $buffer existance..."
else 
    echo "There is no such file in the current folder"
    exit 1
fi
if [ -f $buffer ]; then
    echo "Refreshing the old file..."
    rm $path
    cp $buffer $path
    exit 0
else
    echo "No buffer exists, Creating buffer file"
    cp $path $buffer
    exit 0
fi
# 1 if there are no bufferfile exist, create buffer file



# 2 if buffer file ready, delete old file, cp buffer file

