#!/bin/bash
boostnote="/home/c7031195/Dropbox/Boostnote/"

path_file=$boostnote"notes/c39b9947-b545-4a13-b05f-7b43e54568f8.cson"
rm $path_file"_buffer"
FileSafe $path_file
kill $(ps aux | grep Boostnote|grep boostnote | tr -s ' ' | cut -d ' ' -f2 |cut -d$'\n' -f1)
python $boostnote"notePlugin/daily_review_formal.py"
boostnote &
disown
