#!/bin/bash

dat=$(date +'%Y-%m-%d')
if [ "$#" -ne 1 ]; then
      echo "I take one argument and one argument only: a folder name."
			echo "For current folder, use '.'"
      exit 1
fi
if [[ $1 == '/'* || $1 == '~'* ]]; then
  #    echo $1
      path=$1
  else
      path="$(pwd)/$1"
fi

echo $path
$path/save_page_as "https://www.tesco.com/groceries/en-GB/slots/delivery/${dat}?slotGroup=1" --destination "$path/tesco-buffer.html"

rm $path"/tesco-buffer.html"
